### ISSUE TITLE
Play - what's the interaction to get between 2.1 and 2.2?

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#5]
It's not clear where the hit area should be to move from 2.1 to 2.2. 

![barjeel-app-user-journeys 2-2](https://cloud.githubusercontent.com/assets/1565953/5778325/4c38fac4-9d92-11e4-990e-d7c1a4265e0c.jpeg)

**Comment by clintmclean** [comment]
1. I think we can use swipes and users will figure it out. Seems common on apps.

**Comment by robertocarroll** [comment]
I'd prefer for this first app if we could keep to clear hit areas. 

I can try experimenting with some libraries to get swipe support via JavaScript once we have the first version working, but the support for these libraries (especially on older devices) can be a bit ropey and will need lots of testing. That's why I'd like to push this to the next sprint once we have a working app.

**Comment by UnaJanicijevic** [comment]
Could we just have the screen self advance after a few seconds here, or alternatively build in a NEXT button.

**Comment by clintmclean** [comment]
Swipe is so common (it is on every app i just looked at on my phone) I am a bit worried sultan will ask why we didn't - I guess we'll cross that bridge if it happens. Do you think that may have any bearing on it being accepted in the app store?

**Comment by UnaJanicijevic** [comment]
I'm comfortable with swipe personally.
We could also include a screen with a very simple tutorial on how to navigate, many apps do that though they are generally animated.

**Comment by robertocarroll** [comment]
Screen 2.1 just looks like a potentially confusing error to me: we say "what's the connection?" and then we don't provide any way to answer. Also imagine if you do lots of questions and there's two screens for every question instead of one. It's double the work for the same reward. 

For me 2.1 and 2.2 need to be a single screen, esp with the lack of artist portraits (see #16 )

**Comment by clintmclean** [comment]
Yeah it may need some tweaking. If we were designing just for ipad we could combine the two pages quite easily I think - but for mobile it is becoming very text heavy and doesn't allow for images (see rough example pdf here: https://www.dropbox.com/s/cnuw9m8gnojyy2x/AppDesign-pg5.pdf?dl=0

Let's tentatively proceed as though we are combining the pages but get Una's help on how that will look?

We should also show the artworks in full at the end since this is meant to be educational and is all about the art... Can we make the art circles in 2.4 tappable to open into a full art view?

**Comment by robertocarroll** [comment]
Closing this issue. Fixed in production.
