### ISSUE TITLE
Play - what happens when all lives are lost? 

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#6]
Another screen is necessary to guide the user once they have lost all lives - play again?

**Comment by clintmclean** [comment]
Yeah maybe Would you like to Play Again or Return Home as two options?
I like the idea of the score being shown on this page too.

**Comment by UnaJanicijevic** [comment]
Agreed.
Score + Play Again + Home

**Comment by robertocarroll** [comment]
Please could you provide the design for the "game over" layout.

**Comment by robertocarroll** [comment]
Any news about the design for this game over layout? Thanks.

**Comment by clintmclean** [comment]
Hi Una,
I think you've silenced the github notices (understandably) but are
probably a bit out of the loop on the app as a result.
If you go to this link in google chrome (it has to be chrome for the
developer tools) http://robertocarroll.com/barjeel-app-public/#/play
You will see the app progression and be able to see how things look so far
on different devices.

We had talked a while back about a game over page - can you supply a design
for that? The user would arrive at that page after their third wrong answer
so the page would need to say Sorry, wrong answer. and also Game Over -
Would you like to play again?
Would we want it to say the correct answer that the user died trying to get?

Icon Fonts - I was trying to do these but was getting pretty chunky
versions that weren't nearly usable. I don't know if I was doing it
incorrectly or if icon fonts require very thick graphics with even less
detail than we have. I can try to look into it again but if you know anyone
who may know anything about it maybe see what they think?

As of today I now have the entire barjeel collection in hi-res in a dropbox
so I can access the artworks as needed rather than requesting from Suheyla
- this should be very helpful.
  We have retina and regular images tested in the app and looking good.

Still lots to do but at least on our way. …Sultan today decided he won't
have time for me to do his video before I leave for Canada so I'll provide
direction to a photo studio who does his artwork and they will do it. …so
it won't happen in the next days.

C.

**Comment by clintmclean** [comment]
Here's how to get to the app at the link
http://robertocarroll.com/barjeel-app-public/#/play
Go to the browse menu and select More Tools and then Developer Tools.[image:
Inline image 1]

**Comment by clintmclean** [comment]
Sorry one more thing for the Game Over page is the score.
You scored 5 out of 8 or You got 5 right out of 8 questions or whatever.

**Comment by clintmclean** [comment]
Hi Una
If you go to this link in google chrome (it has to be chrome for the
developer tools) http://robertocarroll.com/barjeel-app-public
You will see the app progression and be able to see how things look so far
on different devices.
When you go to the link, go to chromes little menu icon and choose developer tools to see the app.

We need to get the Game Over page designed which gives Score + Play Again + Home
We also need a design for the Discover posts which should be different from the Connect posts.

I've exported a million sizes of icons for various devices as well as svg's of the icons.
We are still keen to see the icons animate. Can you try putting your frames groups in the layers in illustrator and I will see if I can save as an svg that will work? If we can get one to work then we can do the others.

We have the app working and roughly looking as it should - Rob can put it on one of your devices so you can see it in 'real' life if you send him the necessary info - maybe pop him and email?

I think that's all for now!
C.

**Comment by clintmclean** [comment]
Sorry wrong url
http://robertocarroll.com/barjeel-app/

**Comment by robertocarroll** [comment]
Design for the game over layout: 
![appdesigns-additions](https://cloud.githubusercontent.com/assets/1565953/7675698/71a15e40-fd33-11e4-8606-082bf5c6e4d2.jpg)

Closing this issue.
